### ISSUE TITLE
Quarto Bugs

### ISSUE THREAD

**Issue by priced24** [nakakura24/Quarto_CS301_Fall2022#4]
1. Game randomly flashes red, when placing a piece down, even when it is a legal move.
2. Dumb AI is too smart.
3. Add a list of piece characteristics (shape, color, etc).

-Checkers Group

**Comment by nakakura24** [comment]
1. We believe that the slow draw speed created the illusion that legal moves were flashing. Extensive testing with the now-fixed speed shows that legal moves have not been flashed.
2. Dumb AI is completely random in picking pieces and placing pieces. Quarto is a rather hard game to play for the first few times (we still have to try really hard to beat the dumb AI). We can't make the dumb AI any dumber without complex algorithms.
3. NOT YET SOLVED: we plan to POSSIBLY make it so that hovering over a piece in the pool will show the piece characteristics at the bottom of the screen.

**Comment by nakakura24** [comment]
3. Not solved perfectly, but we believe our solution is sufficient. When a piece is selected to be placed, the bottom of the screen will list the characteristics of the selected piece (along with enlarging the piece).
