### ISSUE TITLE
Team Shogi - Quarto Issues

### ISSUE THREAD

**Issue by priced24** [nakakura24/Quarto_CS301_Fall2022#5]
- Seems like the computer players and human players color set (pieces) change during every new game
- Random red flashes even if legal move
- The computer picked and chose where my piece went

**Comment by nakakura24** [comment]
It appears that these issues stem from a misunderstanding of the game's rules:
1. Any player can pick any color piece (color is simply a characteristic (a means to win)
2. When you select a piece, you are actually selecting the piece for the opponent to place.

As for the red flashes during a legal move, we believe that this issue is a result of the game's slow draw speed which has since been fixed.
